const MDCFoo = mdc.foo.MDCFoo;
const MDCFooFoundation = mdc.foo.MDCFooFoundation;

const countries = [
    'França', 
    'Austrália', 
    'Argentina', 
    'Islândia', 
    'Peru', 
    'Dinamarca', 
    'Croácia', 
    'Nigéria', 
    'Costa Rica', 
    'Sérvia', 
    'Alemanha', 
    'México', 
    'Rússia', 
    'Arábia Saudita', 
    'Egito', 
    'Uruguai', 
    'Marrocos', 
    'Irã', 
    'Portugal', 
    'Espanha', 
    'Brasil', 
    'Suíça', 
    'Suécia', 
    'Coreia do Sul', 
    'Bélgica', 
    'Panamá', 
    'Tunísia', 
    'Inglaterra', 
    'Colômbia', 
    'Japão', 
    'Polônia', 
    'Senegal'
]